services:
  - type: web
    name: image-to-pdf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: temp-storage
      mountPath: /tmp
      sizeGB: 2
